# Generated by Django 2.1.4 on 2018-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollutionmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutiondata',
            name='calculate_aqi_pm10',
        ),
        migrations.RemoveField(
            model_name='pollutiondata',
            name='calculated_aqi_pm25',
        ),
        migrations.AlterField(
            model_name='pollutiondata',
            name='pm10',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pollutiondata',
            name='pm25',
            field=models.FloatField(null=True),
        ),
    ]
